### ISSUE TITLE
Regarding sveltekit#11914

### ISSUE THREAD

**Issue by Kh4n** [TechGunnerINC/TechGunner#5]
You opened [an issue](https://github.com/sveltejs/kit/issues/11914) in SvelteKit regarding a "bug" where your cookies were not being set. The issue is that:

1. Your data flow is like:
```
Frontend browser -> Svelte backend -> ElysiaJS backend
```

So when your ElysiaJS backend sets the cookie in the request [Set-cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie), its passed to the svelte backend, which ignores it, and then the cookie is lost. I can prove this with the following:

```
cookies.set("hello", "hello", {path: ""})
redirect(308, `/profile/${info.data.user.username}`)
```

I added the `cookies.set(...)` line in your svelte backend and it successfully set the cookie. You need to either change the structure of your project or have svelte pass forward the cookie (maybe have elysiajs pass the cookie to set in the response).

As you can see the issue was in fact from your code, not from SvelteKit. The creators and maintainers of these open source projects are very good at what they do, and in my opinion you should almost always assume the issue is on your end unless you can be absolutely sure that its the dependent library's fault.

Another thing: the issue you created was not exactly well received. Pinging dozens of maintainers for a "bug" while refusing to follow the bug report guidelines is not good 😅. Please be respectful to the maintainers of the software that we rely on. It's a mostly thankless job, and their time is precious. Always provide a *minimal* example of the issue when asked. In fact, I'm sure if you had tried to create a minimal example you would have seen the issue yourself!

**Comment by Tech-Gunner** [comment]
I do know how to CRUD cookies from SvelteKit but I want to CRUD cookies from the backend,
and this isn't the major issue the real issue is this one: https://github.com/sveltejs/kit/issues/11924
and I'm sorry for pinging so many people

**Comment by Kh4n** [comment]
I cannot repro that issue. After I setup the db with:
```
bunx prisma migrate dev --name init
```
I get a 200.

> I do know how to CRUD cookies from SvelteKit but I want to CRUD cookies from the backend

This is not possible without you writing some code to make it happen. It is *not* a bug. To re-emphasize, this is what the network path of your request looks like:
```
Frontend browser -> SvelteKit backend -> ElysiaJS backend -> back to SvelteKit -> back to Frontend
```

The cookie header (Set-Cookie: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) is being set by `ElysiaJS backend`. When SvelteKit receives it, it does not do anything with it, and does not forward it either, as that call was made via Axios. You need to do one of the following:
1. Intercept and parse the header out and add it in to the SvelteKit response (not recommended)
2. Don't send back a Set-Cookie header from the ElysiaJS backend at all, and instead send the token back as part of the JSON response and have SvelteKit set it (best)
3. Restructure your code so you don't have 2 backends (SvelteKit and ElysiaJS) (a lot of stuff would have to change)

The way you have it currently set up is completely normal and commonly used. You have a frontend SSR server (SvelteKit) and an API server (ElysiaJS). API servers *do not* set client cookies. That would be the frontend server. In hybrid API/frontend models where there is a single backend, endpoints that return HTML will set cookies, and API endpoints won't.

I *very* strongly recommend reading up on client-server interactions, MDN is a great resource: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_web_server

Absolutely *none* of these issues are due to bugs in Svelte, SvelteKit, Axios, or ElysiaJS. They are entirely related to your code

**Comment by Tech-Gunner** [comment]
can you give a screenshot of the blog route
sveletkit gives 500 when I try to access it

**Comment by grevolution** [comment]
Thanks, @Kh4n for looking into this and helping out. you might have come here from X (just like me 😄) trying to look into the code for @Tech-Gunner and help with the issue. Appreciate you taking time and digging into it.

@Tech-Gunner there is some really good advice for you from @Kh4n in the above comments that'll help you with your journey of coding.

**Comment by sanjaysanjel019** [comment]
I came here after all the Twitter drama. Glad to see @Kh4n helping him out. Tech community is really helpful but it's not a way to ask for advice by opening an issue on the repo when your code itself has the problem @Tech-Gunner. I hope your problem is now solved.

This is really good step from @Kh4n and an appreciative one. Kudos to you brother.

**Comment by Kh4n** [comment]
> can you give a screenshot of the blog route sveletkit gives 500 when I try to access it

I had to make numerous changes to get your code to run. I did not use docker. It seems like there is a misunderstanding of how DBs are supposed to work as well. 

Here is a fork that I made to run your code: https://github.com/Kh4n/TechGunner/tree/fixes

I *do not* recommend pulling this in, as I hardcoded things to make them work, and commented out pieces that were not relevant to debugging.

Here is what I did to make it run:
1. In the frontend folder, all that is needed is `bun install` and `bun run dev`
2. In the backend, you need to
- `bun install`
- `bunx prisma generate`
- start up Postgres locally, I will not explain this here as it is platform dependent and pretty easy, please research this
- use the `psql` command to login and first set a password for the postgres user (I used `password` as the password)
- use the `GRANT` SQL query to grant the postgres user access to the database (may not be necessary)
- once it is setup, run `bunx prisma migrate dev --name init`
- then run `bun run dev`

The `/blogs` route just shows an empty page, with all requests succeeding in the browser dev console.

I am closing this issue now as there is enough info here to get you going, but I again strongly advise learning web basics and client server interactions. It may help to start a simple "todo list" app or so with raw JS and a barebones backend to learn some of the basics, instead of jumping into the deep end with SvelteKit and ElysiaJS. These tools are powerful but abstract away a lot of things which can make it difficult to understand whats going on and make errors stemming from this more complex to resolve.

**Comment by Tech-Gunner** [comment]
Thank you so much @Kh4n for these brilliant changes to my codebase
I'll try my best to follow your advice
You could have used [Supabase](https://supabase.com/) to get a free Postgres DB, I've clearly mentioned the env.exemple file
but anyway thank you
